function feedback = sampleFeedbackText(hitRate)


if hitRate>0.8
    answers = { ...
        'Good job!', ...
        'Well done!', ...
        'You rock!', ...
        'Excellent!', ...
        'Amazing!', ...
        'A++++!',...
        'Outstanding!',...
        'Superb!',...
        'Brilliant!'};
elseif (hitRate>0.6) && (hitRate<=0.8)
    answers = { ...
        'Alright!', ...
        'Keep it up!', ...
        'Stay focused!', ...
        'Nice!', ...
        'You got this!'};
     
elseif (hitRate>0.1) && (hitRate<=0.6)
    answers = { ...
        'Welp!', ...
        'Try to stay awake!', ...
        'Only a few more..', ...
        'Stay focused!', ...
        'You got this!'};
elseif hitRate<=0.1
    answers = {'Don''t worry, this is probably a bug'};
end

idx = randi(length(answers),1);

feedback = answers{idx};
